services:
  postgres:
    image: postgres:17.5
    restart: "no"
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ./db:/docker-entrypoint-initdb.d:ro
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB
      interval: 10s
      timeout: 5s
      start_period: 10s
      retries: 5
  redis:
    image: redis:latest
    restart: "no"
    ports:
      - "${REDIS_PORT}:6379"
    healthcheck:
      test: redis-cli ping
      interval: 10s
      timeout: 5s
      start_period: 10s
      retries: 5
volumes:
  db_data:
